using AutoMapper;
using Cashrewards3API.Common;
using Cashrewards3API.Enum;
using Cashrewards3API.Features.Merchant.Models;
using Cashrewards3API.Mapper;
using FluentAssertions;
using Moq;
using NUnit.Framework;
using System;
using System.Collections.Generic;

namespace Cashrewards3API.Tests.Mapping
{
    [TestFixture]
    public class MerchantProfileTest
    {
        // SELECT DISTINCT [ApprovalTime] FROM [ShopGo].[dbo].[Merchant]
        [Test]
        [TestCase("Up to 95 days from the completion of travel", 95)]
        [TestCase("55 days", 55)]
        [TestCase("Immediate", null)]
        [TestCase("Instant", null)]
        [TestCase("Maximum 30 Days after hotel booking completion. Cashback is guaranteed by Cashrewards.", 30)]
        [TestCase("Once qualifying purchase is approved", null)]
        [TestCase("Once your qualifying transaction has been approved", null)]
        [TestCase("Savings will be applied at the checkout.", null)]
        [TestCase("See Bundll T&Cs", null)]
        [TestCase("Up to 100  Days", 100)]
        [TestCase("Up to 100 Days after travel", 100)]
        [TestCase("Up to 100 Days", 100)]
        [TestCase("Up to 100 days from travel completed", 100)]
        [TestCase("Up to 103 days", 103)]
        [TestCase("Up to 106 days", 106)]
        [TestCase("Up to 107 days", 107)]
        [TestCase("Up to 109 days", 109)]
        [TestCase("Up to 110 days", 110)]
        [TestCase("Up to 111 days", 111)]
        [TestCase("Up to 112 days", 112)]
        [TestCase("Up to 113 days", 113)]
        [TestCase("Up to 115 Days", 115)]
        [TestCase("Up to 115 days from travel completed", 115)]
        [TestCase("Up to 117 days", 117)]
        [TestCase("Up to 119 days", 119)]
        [TestCase("Up to 120 days from travel completed", 120)]
        [TestCase("Up to 120 days", 120)]
        [TestCase("Up to 124 days", 124)]
        [TestCase("Up to 125 days from travel completed", 125)]
        [TestCase("Up to 125 days", 125)]
        [TestCase("Up to 127 days", 127)]
        [TestCase("Up to 130 days", 130)]
        [TestCase("Up to 131 days", 131)]
        [TestCase("Up to 133 days", 133)]
        [TestCase("Up to 135 Days", 135)]
        [TestCase("Up to 136 days", 136)]
        [TestCase("Up to 14 Days", 14)]
        [TestCase("Up to 141 days", 141)]
        [TestCase("Up to 142 days", 142)]
        [TestCase("Up to 144 days", 144)]
        [TestCase("Up to 145 days", 145)]
        [TestCase("Up to 15 days", 15)]
        [TestCase("Up to 150 Days", 150)]
        [TestCase("Up to 150 days from travel completed", 150)]
        [TestCase("Up to 180 Days", 180)]
        [TestCase("Up to 23 days", 23)]
        [TestCase("Up to 24 days", 24)]
        [TestCase("Up to 30 Days from Build Completion", 30)]
        [TestCase("Up to 30 days", 30)]
        [TestCase("Up to 31 days", 31)]
        [TestCase("Up to 37 days", 37)]
        [TestCase("Up to 45 Days", 45)]
        [TestCase("Up to 46 days", 46)]
        [TestCase("Up to 47 days", 47)]
        [TestCase("Up to 49 days", 49)]
        [TestCase("Up to 5 Days", 5)]
        [TestCase("Up to 500 Days", 500)]
        [TestCase("Up to 55 Days after travel", 55)]
        [TestCase("Up to 56 days", 56)]
        [TestCase("Up to 57 days", 57)]
        [TestCase("Up to 59 days", 59)]
        [TestCase("Up to 60 days", 60)]
        [TestCase("Up to 61 days", 61)]
        [TestCase("Up to 62 days", 62)]
        [TestCase("Up to 63 days", 63)]
        [TestCase("Up to 64 days", 64)]
        [TestCase("Up to 65 Days", 65)]
        [TestCase("Up to 66 days", 66)]
        [TestCase("Up to 67 days", 67)]
        [TestCase("Up to 68 days", 68)]
        [TestCase("Up to 69 days", 69)]
        [TestCase("Up to 7 Days", 7)]
        [TestCase("Up to 70 Days", 70)]
        [TestCase("Up to 70 days after the completion of travel", 70)]
        [TestCase("Up to 70 days from rental completion", 70)]
        [TestCase("Up to 70 days from travel completed", 70)]
        [TestCase("Up to 70", 70)]
        [TestCase("Up to 72 days", 72)]
        [TestCase("Up to 73 Days", 73)]
        [TestCase("Up to 74 days", 74)]
        [TestCase("Up to 75 days from travel completed", 75)]
        [TestCase("Up to 75 days", 75)]
        [TestCase("Up to 76 days", 76)]
        [TestCase("Up to 77 days", 77)]
        [TestCase("Up to 78 days", 78)]
        [TestCase("Up to 79 days", 79)]
        [TestCase("Up to 80 days", 80)]
        [TestCase("Up to 82 days", 82)]
        [TestCase("Up to 83 days", 83)]
        [TestCase("Up to 84 days", 84)]
        [TestCase("Up to 85 Days after travel", 85)]
        [TestCase("Up to 85 days", 85)]
        [TestCase("Up to 86 days", 86)]
        [TestCase("Up to 88 days", 88)]
        [TestCase("Up to 89 days", 89)]
        [TestCase("Up to 90 Day5", 90)]
        [TestCase("Up to 90 Days after rental", 90)]
        [TestCase("Up to 90 Days after stay", 90)]
        [TestCase("Up to 90 Days after task completed", 90)]
        [TestCase("Up to 90 Days after travel", 90)]
        [TestCase("Up to 90 Days", 90)]
        [TestCase("Up to 90 days from completed travel", 90)]
        [TestCase("Up to 90 days from travel completed", 90)]
        [TestCase("Up to 94 days", 94)]
        [TestCase("Up to 95  Days", 95)]
        [TestCase("Up to 95 Days after travel", 95)]
        [TestCase("Up to 95 Days after visit", 95)]
        [TestCase("Up to 95 Days", 95)]
        [TestCase("Up to 95 Days70", 95)]
        [TestCase("Up to 95 days after cancellation period", 95)]
        [TestCase("Up to 95 days after completion of travel", 95)]
        [TestCase("Up to 95 days after the completion of travel", 95)]
        [TestCase("Up to 95 days from booking completed", 95)]
        [TestCase("Up to 95 days from rental completion", 95)]
        [TestCase("Up to 95 days from travel completed", 95)]
        [TestCase("Up to 95 days from travel completion", 95)]
        [TestCase("Up to 95days", 95)]
        [TestCase("Up to 96 days", 96)]
        [TestCase("Up to 97 days", 97)]
        [TestCase("Up to 98 days", 98)]
        public void GetApprovalTime_FromString(string str, int? expected) 
        {
            int? days = MerchantProfile.GetApprovalTime(str);
            days.Should().Be(expected);
        }

        // SELECT DISTINCT [TrackingTime] FROM [ShopGo].[dbo].[Merchant]
        [Test]
        [TestCase("1 to 14 Days", 14)]
        [TestCase("1 to 14 days after activation", 14)]
        [TestCase("1 to 21 Days", 21)]
        [TestCase("1 to 25 Days", 25)]
        [TestCase("1 to 30 Days", 30)]
        [TestCase("1 to 7 Days from purchase date", 7)]
        [TestCase("1 to 7 Days", 7)]
        [TestCase("1 to 7 Dayswww.mybag.com", 7)]
        [TestCase("14 Days", 14)]
        [TestCase("21 Days from shipping", 21)]
        [TestCase("3 Days", 3)]
        [TestCase("30 Days", 30)]
        [TestCase("7 to 14 Days", 14)]
        [TestCase("Cashback will report after your stay has been completed", null)]
        [TestCase("Immediate", null)]
        [TestCase("Instant", null)]
        [TestCase("Not a cashback offer", null)]
        [TestCase("See Bundll T&Cs", null)]
        [TestCase("Up to 1 Day", 1)]
        [TestCase("Up to 10 Days", 10)]
        [TestCase("Up to 30 Days", 30)]
        [TestCase("Up to 4 days", 4)]
        [TestCase("Up to 60 Days", 60)]
        [TestCase("Up to 7 Days after product is shipped", 7)]
        [TestCase("Up to 7 Days from Shipping", 7)]
        [TestCase("Up to 7 Days", 7)]
        [TestCase("Up to 95 days from travel completed", 95)]
        public void GetTrackingTimeMax_FromString(string str, int? expected)
        {
            int? days = MerchantProfile.GetTrackingTimeMax(str);
            days.Should().Be(expected);
        }

        // SELECT DISTINCT [TrackingTime] FROM [ShopGo].[dbo].[Merchant]
        [Test]
        [TestCase("1 to 14 Days", 1)]
        [TestCase("1 to 14 days after activation", 1)]
        [TestCase("1 to 21 Days", 1)]
        [TestCase("1 to 25 Days", 1)]
        [TestCase("1 to 30 Days", 1)]
        [TestCase("1 to 7 Days from purchase date", 1)]
        [TestCase("1 to 7 Days", 1)]
        [TestCase("1 to 7 Dayswww.mybag.com", 1)]
        [TestCase("14 Days", null)]
        [TestCase("21 Days from shipping", null)]
        [TestCase("3 Days", null)]
        [TestCase("30 Days", null)]
        [TestCase("7 to 14 Days", 7)]
        [TestCase("Cashback will report after your stay has been completed", null)]
        [TestCase("Immediate", null)]
        [TestCase("Instant", null)]
        [TestCase("Not a cashback offer", null)]
        [TestCase("See Bundll T&Cs", null)]
        [TestCase("Up to 1 Day", null)]
        [TestCase("Up to 10 Days", null)]
        [TestCase("Up to 30 Days", null)]
        [TestCase("Up to 4 days", null)]
        [TestCase("Up to 60 Days", null)]
        [TestCase("Up to 7 Days after product is shipped", null)]
        [TestCase("Up to 7 Days from Shipping", null)]
        [TestCase("Up to 7 Days", null)]
        [TestCase("Up to 95 days from travel completed", null)]
        public void GetTrackingTimeMin_FromString(string str, int? expected)
        {
            int? days = MerchantProfile.GetTrackingTimeMin(str);
            days.Should().Be(expected);
        }
    }
}